#!/bin/bash

FILESIZE=200 #GB
NR_READ_PAGES_VAR=128
NR_THREADS_VAR=16
NR_STRIDE=64 #nr_pages
NR_RA_PAGES=1024L #nr_pages

mkdir bin
make -j SIZE=$FILESIZE NR_READ_PAGES=$NR_READ_PAGES_VAR NR_THREADS=$NR_THREADS_VAR NR_STRIDE=$NR_STRIDE NR_RA_PAGES=$NR_RA_PAGES
